version: "3.9"
services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  app:
    build:
      context: .
    container_name: shorten_links_app
    command: ["/app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - network

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

networks:
  network:
    driver: bridge

volumes:
  postgres_data: